# Generated by Django 4.0 on 2023-06-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_supplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
