# Generated by Django 4.1.7 on 2023-03-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='medicine',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(max_length=20, null=True),
        ),
    ]
