# Generated by Django 4.1.7 on 2023-04-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap', '0003_products_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='manufacture_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
